commom: &commom
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *commom
  database: account_manager_development

test:
  <<: *commom
  database: account_manager_test